package xxhlp.oracle.apps.xxhlp.recruit.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class eduLVORowImpl extends OAViewRowImpl {
    public static final int EDU = 0;
    public static final int EDUDESC = 1;

    /**This is the default constructor (do not remove)
     */
    public eduLVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Edu
     */
    public String getEdu() {
        return (String) getAttributeInternal(EDU);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Edu
     */
    public void setEdu(String value) {
        setAttributeInternal(EDU, value);
    }

    /**Gets the attribute value for the calculated attribute EduDesc
     */
    public String getEduDesc() {
        return (String) getAttributeInternal(EDUDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EduDesc
     */
    public void setEduDesc(String value) {
        setAttributeInternal(EDUDESC, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EDU:
            return getEdu();
        case EDUDESC:
            return getEduDesc();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EDU:
            setEdu((String)value);
            return;
        case EDUDESC:
            setEduDesc((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
