package xxhlp.oracle.apps.xxhlp.recruit.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class exptypeLVORowImpl extends OAViewRowImpl {
    public static final int EXPTYPE = 0;
    public static final int EXPTYPEDESC = 1;

    /**This is the default constructor (do not remove)
     */
    public exptypeLVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Exptype
     */
    public String getExptype() {
        return (String) getAttributeInternal(EXPTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Exptype
     */
    public void setExptype(String value) {
        setAttributeInternal(EXPTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute ExptypeDesc
     */
    public String getExptypeDesc() {
        return (String) getAttributeInternal(EXPTYPEDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ExptypeDesc
     */
    public void setExptypeDesc(String value) {
        setAttributeInternal(EXPTYPEDESC, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EXPTYPE:
            return getExptype();
        case EXPTYPEDESC:
            return getExptypeDesc();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EXPTYPE:
            setExptype((String)value);
            return;
        case EXPTYPEDESC:
            setExptypeDesc((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
