package xxhlp.oracle.apps.xxhlp.recruit.server;

import java.util.List;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class expVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public expVOImpl() {
    }
  
}
