package xxhlp.oracle.apps.xxhlp.recruit.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;

import xxhlp.oracle.apps.xxhlp.recruit.schema.server.expEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class expVORowImpl extends OAViewRowImpl {
    public static final int ROWID1 = 0;
    public static final int APPEMPID = 1;
    public static final int APPID = 2;
    public static final int COMPANYNAME = 3;
    public static final int DATEFROM = 4;
    public static final int DATEUPTO = 5;
    public static final int POSITIONHELD = 6;
    public static final int COUNTRY = 7;
    public static final int COUNTRYDESC = 8;
    public static final int EXPTYPE = 9;
    public static final int EXPTYPEDESC = 10;
    public static final int ATTRIBUTECATEGORY = 11;
    public static final int ATTRIBUTE1 = 12;
    public static final int ATTRIBUTE2 = 13;
    public static final int ATTRIBUTE3 = 14;
    public static final int ATTRIBUTE4 = 15;
    public static final int ATTRIBUTE5 = 16;
    public static final int ATTRIBUTE6 = 17;
    public static final int ATTRIBUTE7 = 18;
    public static final int ATTRIBUTE8 = 19;
    public static final int ATTRIBUTE9 = 20;
    public static final int ATTRIBUTE10 = 21;
    public static final int ATTRIBUTE11 = 22;
    public static final int ATTRIBUTE12 = 23;
    public static final int ATTRIBUTE13 = 24;
    public static final int ATTRIBUTE14 = 25;
    public static final int ATTRIBUTE15 = 26;
    public static final int CREATEDBY = 27;
    public static final int CREATIONDATE = 28;
    public static final int LASTUPDATEDBY = 29;
    public static final int LASTUPDATEDATE = 30;
    public static final int LASTUPDATELOGIN = 31;
    public static final int EXPYEARS = 32;
    public static final int EXPYEAR = 33;

    /**This is the default constructor (do not remove)
     */
    public expVORowImpl() {
    }

    /**Gets expEO entity object.
     */
    public expEOImpl getexpEO() {
        return (expEOImpl)getEntity(0);
    }

    /**Gets the attribute value for the calculated attribute RowId1
     */
    public RowID getRowId1() {
        return (RowID) getAttributeInternal(ROWID1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RowId1
     */
    public void setRowId1(RowID value) {
        setAttributeInternal(ROWID1, value);
    }

    /**Gets the attribute value for APP_EMP_ID using the alias name AppEmpId
     */
    public Number getAppEmpId() {
        return (Number) getAttributeInternal(APPEMPID);
    }

    /**Sets <code>value</code> as attribute value for APP_EMP_ID using the alias name AppEmpId
     */
    public void setAppEmpId(Number value) {
        setAttributeInternal(APPEMPID, value);
    }

    /**Gets the attribute value for APP_ID using the alias name AppId
     */
    public Number getAppId() {
        return (Number) getAttributeInternal(APPID);
    }

    /**Sets <code>value</code> as attribute value for APP_ID using the alias name AppId
     */
    public void setAppId(Number value) {
        setAttributeInternal(APPID, value);
    }

    /**Gets the attribute value for COMPANY_NAME using the alias name CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**Gets the attribute value for DATE_FROM using the alias name DateFrom
     */
    public Date getDateFrom() {
        return (Date) getAttributeInternal(DATEFROM);
    }

    /**Sets <code>value</code> as attribute value for DATE_FROM using the alias name DateFrom
     */
    public void setDateFrom(Date value) {
        setAttributeInternal(DATEFROM, value);
    }

    /**Gets the attribute value for DATE_UPTO using the alias name DateUpto
     */
    public Date getDateUpto() {
        return (Date) getAttributeInternal(DATEUPTO);
    }

    /**Sets <code>value</code> as attribute value for DATE_UPTO using the alias name DateUpto
     */
    public void setDateUpto(Date value) {
        setAttributeInternal(DATEUPTO, value);
    }

    /**Gets the attribute value for POSITION_HELD using the alias name PositionHeld
     */
    public String getPositionHeld() {
        return (String) getAttributeInternal(POSITIONHELD);
    }

    /**Sets <code>value</code> as attribute value for POSITION_HELD using the alias name PositionHeld
     */
    public void setPositionHeld(String value) {
        setAttributeInternal(POSITIONHELD, value);
    }

    /**Gets the attribute value for COUNTRY using the alias name Country
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**Sets <code>value</code> as attribute value for COUNTRY using the alias name Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**Gets the attribute value for the calculated attribute CountryDesc
     */
    public String getCountryDesc() {
        return (String) getAttributeInternal(COUNTRYDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CountryDesc
     */
    public void setCountryDesc(String value) {
        setAttributeInternal(COUNTRYDESC, value);
    }

    /**Gets the attribute value for EXP_TYPE using the alias name ExpType
     */
    public String getExpType() {
        return (String) getAttributeInternal(EXPTYPE);
    }

    /**Sets <code>value</code> as attribute value for EXP_TYPE using the alias name ExpType
     */
    public void setExpType(String value) {
        setAttributeInternal(EXPTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute ExpTypeDesc
     */
    public String getExpTypeDesc() {
        return (String) getAttributeInternal(EXPTYPEDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ExpTypeDesc
     */
    public void setExpTypeDesc(String value) {
        setAttributeInternal(EXPTYPEDESC, value);
    }

    /**Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute ExpYears
     */
    public Number getExpYears() {
        return (Number) getAttributeInternal(EXPYEARS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ExpYears
     */
    public void setExpYears(Number value) {
        setAttributeInternal(EXPYEARS, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            return getRowId1();
        case APPEMPID:
            return getAppEmpId();
        case APPID:
            return getAppId();
        case COMPANYNAME:
            return getCompanyName();
        case DATEFROM:
            return getDateFrom();
        case DATEUPTO:
            return getDateUpto();
        case POSITIONHELD:
            return getPositionHeld();
        case COUNTRY:
            return getCountry();
        case COUNTRYDESC:
            return getCountryDesc();
        case EXPTYPE:
            return getExpType();
        case EXPTYPEDESC:
            return getExpTypeDesc();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case ATTRIBUTE11:
            return getAttribute11();
        case ATTRIBUTE12:
            return getAttribute12();
        case ATTRIBUTE13:
            return getAttribute13();
        case ATTRIBUTE14:
            return getAttribute14();
        case ATTRIBUTE15:
            return getAttribute15();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case EXPYEARS:
            return getExpYears();
        case EXPYEAR:
            return getExpYear();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            setRowId1((RowID)value);
            return;
        case APPEMPID:
            setAppEmpId((Number)value);
            return;
        case APPID:
            setAppId((Number)value);
            return;
        case COMPANYNAME:
            setCompanyName((String)value);
            return;
        case DATEFROM:
            setDateFrom((Date)value);
            return;
        case DATEUPTO:
            setDateUpto((Date)value);
            return;
        case POSITIONHELD:
            setPositionHeld((String)value);
            return;
        case COUNTRY:
            setCountry((String)value);
            return;
        case COUNTRYDESC:
            setCountryDesc((String)value);
            return;
        case EXPTYPE:
            setExpType((String)value);
            return;
        case EXPTYPEDESC:
            setExpTypeDesc((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case ATTRIBUTE11:
            setAttribute11((String)value);
            return;
        case ATTRIBUTE12:
            setAttribute12((String)value);
            return;
        case ATTRIBUTE13:
            setAttribute13((String)value);
            return;
        case ATTRIBUTE14:
            setAttribute14((String)value);
            return;
        case ATTRIBUTE15:
            setAttribute15((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case EXPYEARS:
            setExpYears((Number)value);
            return;
        case EXPYEAR:
            setExpYear((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute ExpYear
     */
    public Boolean getExpYear() {
        return (Boolean) getAttributeInternal(EXPYEAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ExpYear
     */
    public void setExpYear(Boolean value) {
        setAttributeInternal(EXPYEAR, value);
    }
}
